### ISSUE TITLE
Thrashes server w/ react-apollo and babel 7

### ISSUE THREAD

**Issue by mike-marcacci** [gajus/babel-plugin-graphql-tag#19]
- `babel-plugin-graphql-tag`: ^1.6.0
- `react-apollo`: ^2.1.5
- `@babel/*`: ^7.0.0-beta.54

We added `babel-plugin-graphql-tag` to our workflow yesterday, but with the above configuration the apollo react components think the query has changed on each render, causing total API thrashing.

We just reverted for now, but it's likely that the query needs to be hoisted out to a permanent scope. This is (obviously) something that can be done manually, but ideally would be handled by the plugin, since it's not obvious to a developer that the string template is in fact compiled into an object with a distinct identity.

EDIT: to clarify, this will thrash:

```js
SomeComponent = () => (
  <Query query={gql`
    query SomeQuery($id: ID!) {
      node(id: $id) {
    }
  `} >...</Query>
);

```

while this works as intended
```js
const query = gql`
  query SomeQuery($id: ID!) {
    node(id: $id) {
  }
`;

SomeComponent = () => (
  <Query query={query} >...</Query>
);

```

**Comment by gajus** [comment]
As far as I can see, this isn't `babel-plugin-graphql-tag` specific. This will happen if you us `gql` tag. I think that hoisting this might produce unexpected results, e.g. when the true intent is to create a new query object every time the tag is constructed. Therefore, I suggest to simply hoist the code as per your own suggestion.

**Comment by awinograd** [comment]
Not to needlessly dig up an old issue, but I just ran into the same problem. Adding this babel plugin was causing my apollo `useQuery` hook to re-render infinitely.

The main difference is that `graphql-tag` maintains a cache so it doesn't return a new reference every time it's called.

https://github.com/apollographql/graphql-tag#caching-parse-results

Might be nice to have a warning in the README, but maybe not worth it if I'm the only person to stumble back here in a year and a half :)

Thanks for the library!
