### ISSUE TITLE
Support Babel7

### ISSUE THREAD

**Issue by slorber** [gajus/babel-plugin-graphql-tag#24]
Hi,

Just wondering if this lib will work with Babel7? if yes, that could be handy to add to readme ;)

**Comment by gajus** [comment]
It does.

**Comment by fracmak** [comment]
I've run into a problem with babel 7 + babel-istanbul + webpack and this plugin. All the functions added to the code get large numbers of incorrect codecov markers most of which don't exist in the file being processed. It looks like some internal structure is being shared between all the transformed code so the output is corrupted.
