### ISSUE TITLE
Basic example throws error "GraphQL query must have name"

### ISSUE THREAD

**Issue by nhunzaker** [gajus/babel-plugin-graphql-tag#3]
From the readme:

```javascript
import gql from 'graphql-tag';

const foo = gql`query {bar}`;
```

This throws:

```javascript
error Error: GraphQL query must have name.
```

The `graphql-tag` library itself doesn't require a query to be named. What are your thoughts on skipping this validation, or making it an option?

**Comment by nhunzaker** [comment]
Actually, I'd be happy to do this work if you're on board with the change.

**Comment by gajus** [comment]
Have a go at it.

**Comment by taras** [comment]
Is this issue resolved?

**Comment by nhunzaker** [comment]
Hey! Yep! I'm using this on my current project. I never followed up regarding this issue.

Thanks for the ping!
