### ISSUE TITLE
No difference in the build size results

### ISSUE THREAD

**Issue by samuelcastro** [gajus/babel-plugin-graphql-tag#40]
Hi, I'm using this plugin in a relatively small project (https://github.com/UnlyEd/next-right-now/pull/56), the issue we're facing is that we're not seeing any difference in the build size results after enabling it. 

Btw, I'm aware of the [fragments requirements usage](https://github.com/gajus/babel-plugin-graphql-tag#using-fragments).

More context:

**Without the plugin:** 

<img width="1918" alt="Screen Shot 2020-05-20 at 3 46 40 PM" src="https://user-images.githubusercontent.com/3807458/82413048-f8d7d680-9a74-11ea-9c44-56821e0003c5.png">

**Using the plugin:**

<img width="1918" alt="Screen Shot 2020-05-20 at 3 46 40 PM" src="https://user-images.githubusercontent.com/3807458/82413115-1ad15900-9a75-11ea-894d-3cca925cbffc.png">

Any feedback?

Thanks!

**Comment by gajus** [comment]
Too obscure question. You will need to dig deeper into analysing the build to see what is getting included.

**Comment by CarlPhilippe** [comment]
If you use @apollo/client v3 it will include graphql-tag even after using this plugin. 
It seems related to https://github.com/apollographql/apollo-client/pull/5451
