### ISSUE TITLE
Bypass the plugin

### ISSUE THREAD

**Issue by DanielHoffmann** [gajus/babel-plugin-graphql-tag#46]
Is there any official way to bypass this plugin for places where we need to dynamically create the queries?

For example I have some code where I let the users pick the fields he wants to see in a table and manually build the query based on that. I can't create a query at compile time because there are too many fields to do all the combinations of fields selected

**Comment by gajus** [comment]
If you are bypassing this plugin for some queries, then using this plugin does not make much sense for the rest of them. The main benefit of this plugin is that it will remove `graphql-tag` dependency. If even one query is dynamic, then you need that dependency.

**Comment by DanielHoffmann** [comment]
Compiling the queries at runtime adds a lot of impact as well. Especially if you do a lot of fragment mashing together like I am in my project.

Also graphql-tag itself is really small (<1kb), what is big bundle-wise is `graphql` which is used by graphql-tag. If you use Apollo you need `graphql` itself anyway, then why is it recommended in Apollo docs:

https://www.apollographql.com/docs/react/performance/babel/

?

**Comment by gajus** [comment]
I am happy to accept an enhancement that would allow to skip certain queries, i.e. by marking some queries with a comment.
