### ISSUE TITLE
Changelog please

### ISSUE THREAD

**Issue by steelbrain** [gajus/babel-plugin-graphql-tag#49]
Hello @gajus 

Thank you for working on this.

The lack of a changelog file and the lack of tagged releases makes it difficult to upgrade this package in dependents. Are you open to the idea of changelogs?

Cheers

**Comment by kachkaev** [comment]
I'm afraid the problem is still present. Currently on `2.5.0`, not sure what to be cautions about to upgrade to `3.1.0`.

Diff between 2.5.0 and 3.0.0: https://github.com/gajus/babel-plugin-graphql-tag/compare/v2.5.0...e76450c2cf667ebdac85dc34a0dc5d3fce64ec8c
