### ISSUE TITLE
Support for concatenating fragments

### ISSUE THREAD

**Issue by leoasis** [gajus/babel-plugin-graphql-tag#5]
Hi!

I've recently created https://github.com/leoasis/graphql-tag.macro which is kind of the same as this library but using [babel-macros](https://github.com/kentcdodds/babel-macros).

One thing that I added in my lib is support for concatenating definitions from interpolated values in the tagged string literal. This allows to interpolate fragments in particular. You can see the implementation [here](https://github.com/leoasis/graphql-tag.macro/blob/master/src/index.macro.js#L28-L40). 

Would you be willing to accept a PR adding this feature to this plugin so people that prefer plain babel plugins can benefit from this?

**Comment by gajus** [comment]
> Would you be willing to accept a PR adding this feature to this plugin so people that prefer plain babel plugins can benefit from this?

Of course.

**Comment by leoasis** [comment]
PR issued! 😄
