### ISSUE TITLE
What breaking changes, if any, were there in v3?

### ISSUE THREAD

**Issue by MatthewHerbst** [gajus/babel-plugin-graphql-tag#53]
Moving from v2 to v3 generally implies a breaking change, though there is no CHANGELOG/HISTORY file or updated Releases. Could you please let us know what breaking changes (if any) are present when going from v2 -> v3? Thank you!

**Comment by gajus** [comment]
Dropped Node.js v8 support.

**Comment by MatthewHerbst** [comment]
Thanks for the quick response!
