### ISSUE TITLE
GraphQL as peerDep

### ISSUE THREAD

**Issue by bkniffler** [gajus/babel-plugin-graphql-tag#7]
Hey, I'm getting 
```
Uncaught Error: Cannot use e "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
```

I suppose its due to the babel-plugin using 0.10.5 while my app uses >1.0.0. Could we get rid of the dependency in the plugin?

**Comment by gajus** [comment]
The appropriate thing to do here is to update the dependency.

I am not familiar though with what were the breaking changes.

**Comment by jaydenseric** [comment]
It should be a peer dep.

**Comment by bkniffler** [comment]
I think its safe to assume that people who implement this plugin would install graphql and graphql-tag themselves, just as you'd assume people will install react when you create and publish some react component. Thats why most react components will have react in their peerDependencies.

**Comment by jaydenseric** [comment]
@gajus Awesome 🙌

Any chance we could bump the `graphql` peer dep up to version `0.11 - 0.12`, or will that involve a bit of compatibility work?

**Comment by gajus** [comment]
> Any chance we could bump the graphql peer dep up to version 0.11 - 0.12, or will that involve a bit of compatibility work?

No clue. Didn't touch it as part of this change.
